### ISSUE TITLE
Content blocked

### ISSUE THREAD

**Issue by salazarjoelo** [greyaz/EmbedAnything#1]
Hi there. Congrats for your excellent plugin.
I tried it on my kanboard instance but I have an "Content blocked" message Any clue for solve it?

**Comment by greyaz** [comment]
Hi @salazarjoelo ,

Can you provide more detials about the problem you met?

**Comment by salazarjoelo** [comment]
Hi @greyaz Thanks for your answer.
Wel I have a kanboard instance, I installed succesfully your plugin EmbedAnything, changed config file with the url I want to watch. I see your plugin tab named "Metabase" on the panel and renamed it to my own needing but I do not see the embeeded content, just a message: This content is blocked
This is the url I want to see and It shows normally
https://simontse.mx.nf/red/
Any idea about this issue? Thanks in advance

**Comment by greyaz** [comment]
@salazarjoelo 

I guess this is an issue caused by the CSP settings on your server.
If you are using Chrome, you can press F12 frome the page you met the issue, then goto the tab "console", check if there is any error message.

**Comment by salazarjoelo** [comment]
Thanks for your answer @greyaz 
I will check it as you sugest to me.

**Comment by greyaz** [comment]
@salazarjoelo 
The CSP will be updated automatically according to your configs in the newest version: 0.3.0.
If your problem was really caused by CSP, it should be fixed now.
Please have a try after being merged to the official repository and tell me the results.

**Comment by salazarjoelo** [comment]
Great job @greyaz !!! It is working now with external urls. Thanks!!!

**Comment by greyaz** [comment]
you are welcome
